### ISSUE TITLE
Introductory header: Quick Overview of Mobility Mapper

### ISSUE THREAD

**Issue by SonyaJane** [SonyaJane/mobility-mapper#3]
**User story** 
As a busy carer of a mobility impaired person, I want to quick overview of mobility mapper so that I can determine if it's the kind of tool I'm looking for, and if it's worth my time learning more about it.

**Acceptance Criteria**
- [ ] The top of the homepage features a concise overview that explains the app’s purpose and how it benefits users of wheeled mobility devices.
- [ ] A prominent call-to-action is available to enable the visitor to subscribe to email updates, providing them with more information and a prompt to return to the website when they have more time to dive deeper.

**Tasks**
- [ ] Create a semantic HTML header
- [ ] Add a hero image of a wheeler with a tagline
- [ ] Add a non-visible h1 heading "Mobility Mapper" for SEO purposes (the logo acts as the main heading)
- [ ] Add a "Subscribe to email updates" button that opens a modal containing a form so that the visitor can remain on the homepage when they have completed (or dismissed) the form.
- [ ] write a short overview of the app
