### ISSUE TITLE
Pitch the app to Potential Funders, Partners, and Stakeholders

### ISSUE THREAD

**Issue by SonyaJane** [SonyaJane/mobility-mapper#5]
**User story** 
As a potential funder, partner, or stakeholder, I want to understand the value, impact, and business potential of the Mobility Mapper app so that I can evaluate whether it aligns with my goals and is worth my support or aligns with our funding objectives.

**Acceptance Criteria**
- [ ] A dedicated page on the website provides a clear and compelling pitch for Mobility Mapper. 
- [ ] An introduction describes the problems the app solves for wheelersand how it solves them
- [ ] There is a section on market potential, and the app’s expected social and economic impact 
- [ ] There is content differentiating Mobility Mapper from other navigation apps.
- [ ] The page includes clear, compelling visuals that highlight the app’s purpose and impact.
- [ ] Clear calls to action for funding inquiries and contact information are present
- [ ] Clear links on the homepage inviting the visitor to go to the partnerships page 

**Tasks**
- [ ] Create a “Partnerships and Funding” page based on the supplied pitch text  
- [ ] Create a "Problem" section
- [ ] Create a "Solution" section
- [ ] Create a sections titled "Market Size" and "Market validation". Use quotes from trusted sources to build credibility and demonstrate early interest or validation.
- [ ] Add a section differentiating Mobility Mapper from other navigation apps.
- [ ] Create a sections about who else MM will benefit
- [ ] Add a form and direct contact information for partnership funding inquiries.
- [ ] Add a button at the top and bottom of the page that take the visitor to the partnerships and funding page
