### ISSUE TITLE
Subscribe to email updates button

### ISSUE THREAD

**Issue by SonyaJane** [SonyaJane/mobility-mapper#6]
**User story** 
As a potential user or supporter, I want to sign up for updates about the app’s progress and launch so I can stay informed and be notified when the app is available.

**Acceptance Criteria**
- [ ] A prominent call-to-action is available to enable the visitor to subscribe to email updates.
- [ ] A confirmation of subscription is shown on clicking the submit button

**Tasks**
- [ ] Add a "Subscribe to email updates" button that opens a modal containing a form so that the visitor can remain on the homepage when they have completed (or dismissed) the form.
- [ ]  Create a confirmation of subscription
